[package]
name = "algebraic_float"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {
    version = "1.0.229",
    features = ["serde_derive"],
    default-features = false,
    optional = true
}
num-traits = {
    version = "0.2.19",
    optional = true
}
duplicate = "2.0.1"

[features]
default = ["num", "serde"]
num = ["dep:num-traits"]
serde = ["dep:serde"]
