[package]
name = "algebraic_float"
description = "Wrapper type over floating point numbers that treats them like real numbers. This allows the compiler to exploit algebraic properties of the real numbers like associativity etc. This can result in shallower dependency depth in the output assembly code, or in the case of loops can help the compiler to perform SIMD vectorisation."
repository = "https://github.com/Vivian-McKnight/real_float"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {
    version = "1.0.229",
    features = ["serde_derive"],
    default-features = false,
    optional = true
}
num-traits = {
    version = "0.2.19",
    optional = true
}
duplicate = "2.0.1"

[features]
default = ["num", "serde"]
num = ["dep:num-traits"]
serde = ["dep:serde"]
